### ISSUE TITLE
another glow effect is added to models every second

### ISSUE THREAD

**Issue by kirillbrest123** [bloodycop6385/glowlib#1]
title
![20240707120709_1](https://github.com/bloodycop7/glowlib/assets/70514395/6b8f3fdf-0d52-4af7-bbed-dd7098bc355b)

**Comment by bloodycop6385** [comment]
Honestly, what the fuck?? I cannot reproduce this.

**Comment by bloodycop6385** [comment]
@kirillbrest123 Try disabling all your addons, restart your game and do this again.
